blank_issues_enabled: false
contact_links:
  - name: Twitter
    url: https://twitter.com/ShuklaRitvik06
    about: Please ask and answer questions here.
  - name: GitHub
    url: https://github.com/shuklaritvik06
    about: Please report security vulnerabilities here.
